# Generated by Django 5.2.6 on 2025-09-14 05:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_code",
                    models.CharField(max_length=10, unique=True, verbose_name="รหัสห้อง"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อห้อง")),
                ("capacity", models.PositiveIntegerField(verbose_name="ความจุ")),
                (
                    "start_time_available",
                    models.TimeField(
                        default=datetime.time(8, 0), verbose_name="เวลาเริ่มเปิดให้จอง"
                    ),
                ),
                (
                    "end_time_available",
                    models.TimeField(
                        default=datetime.time(17, 0), verbose_name="เวลาสิ้นสุดการจอง"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "เปิดให้จอง"), ("closed", "ปิดให้จอง")],
                        default="open",
                        max_length=10,
                        verbose_name="สถานะ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="เวลาที่ทำรายการ"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="เวลาเริ่มต้น")),
                ("end_time", models.TimeField(verbose_name="เวลาสิ้นสุด")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้จอง",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.room",
                        verbose_name="ห้องที่จอง",
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "start_time"), ("user", "room")},
            },
        ),
    ]
