# Generated by Django 5.2.6 on 2025-09-14 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_room_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(default=datetime.date.today, verbose_name="วันที่จอง"),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("room", "booking_date", "start_time")},
        ),
    ]
